# -*- coding: utf-8 -*-
"""day-7-assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/SaiSravya6/82fb3bf7d13a943faf3f036f07c35e65/day-7-assignment.ipynb
"""

print('data')

x=5
while x>10:
  print('data')
print(x)

x=5
while x>10:
  print('yes')
print(x)

x=5
while x<10:
  print('yes',x)
  x=x+1

x=5
while x<10:
  print('yes',x)
  x+=1

x=x+1

y=[4,2,8,5,3,6,9]
y

x=[5,6,7,8,9]
x

y**2

y=[40,20,80,50,30,60,90]
y

3*85

10*85

y*8

y*5

y*2

for i in y:
  print(i)

for h in y:
  print(h)

for s in y:
  print(s)

for i in y:
  print(i*85)

40*5+10

y=[40,20,80,50,30,60,90]
y

y*5

20*5+10

80*5+10

50*5+10

30*5+10

60*5+10

90*5+10

for x in y:
  t = print(x*5+10)

for i in y:
  print(i*5+10)

z=[]
for i in y:
  print(i*5+10)

z=[]
for i in y:
  z.append(i*5+10)

z

num=[31,45,66,33,90,78,67,87,89,93,25,59,9,81]
num

x=[]
y=[]
for i in num:
  if i%2==0:
    x.append(i)
  else:
    y.append(i)

x

y

num

str(31)

t=str(31)
t

h=[]
for i in num:
  a=str(i)
  b=a.replace('8','5')
  h.append(b)
  print(b)

h

h=[]
for i in num:
  a=str(i)
  b=a.replace('8','5')
  c=int(b)
  h.append(c)

h

t.replace('3','5')

f=t.replace('3','5')
f