# -*- coding: utf-8 -*-
"""day-14-assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/SaiSravya6/175268277f4c544fa3cd522c2b24c0b5/day-14-assignment.ipynb
"""

from pandas import read_csv
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import chi2,f_regression
dataframe=sns.load_dataset('tips')
dataframe

dataframe=sns.load_dataset('tips')
dataframe

from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
lb

from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
dataframe['Gender']=lb.fit_transfrom(dataframe['Gender'])
dataframe['smoke']=lb.fit_transfrom(dataframe['smoke'])
dataframe['day']=lb.fit_transfrom(dataframe['day'])
dataframe['time']=lb.fit_transfrom(dataframe['time'])

X = dataframe.iloc[:,1:]
Y = dataframe.iloc[:,0]
X

Y