# -*- coding: utf-8 -*-
"""DAY-1 ASSIGNEMENT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLPSAc1jC7ozE_5Ukj3PIUXsxH1vaF6Y
"""

a={101:1,104:2,105:3}
a

a[101]

b={'name':'Sravya','id':65,'age':20}
b

b['id']=93
b

b.update({102:99})
b

b[101]=9
b

b.update({'age':20})
b

b.get(102)
b

b[105]=5000
b

b[101]=9
b

b.get(105)
b

b.update({101:'India'})
b

b.update({106:'India'})
b

x = {501:4, 502:6, 'id':63, 501:89}
x

x.update({'id':96})
x

x.get(502)