# -*- coding: utf-8 -*-
"""day-2-assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/SaiSravya6/12d1aa6221bf10f489a8d37e2eece193/day-2-assignment.ipynb
"""

[24]:

a=[93,5.5,'Python','True','63']
a

a[0:2]

a[0:4]

a[1:5]

a[-1]

a[-1:5]

a[0:-4]

a[0:-4:1]

a[-1:-4:-1]

a[1:4:1]

a[2:4:1]

a[-2:-4:-1]

a=[93,'True','Ayush',8.9,'Hyderabad']
a

a.insert(93,53)
a

a.append(63)
a

a.pop(6)
a

a.extend('Sravya')
a
print(a)

x=(45,5.5,89,67,98)
print(x)

x[-2:-5:-1]

x.count(89)

x.index(98)

x[0]

x[1:7]

x[1:8]

x[2]

x[-5]

x[1:4:1]

x[-5]

x[-1:-4:-1]

x[-2:-5:-1]

z={"name":"Ayush","age":14,"id":45}
z

z.pop("name")

z["age"]

z["id"]

z["marks"]=98
z

