# -*- coding: utf-8 -*-
"""DAY-5 ASSIGNMENT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cFKMjlXLYZldruPCb2bMnh-iIzGSO8N3
"""

d={101:4,102:7,'B':2}
d

d['B']

d[101]

d.update({102:99})
d

d[105]=500
d

d[105]=5000
d

d.get(105)

d[101]='India'
d

d.get(101)

type(d)

type(d[102])

d[104]=[123,345,567,789]
d

type(d[104])

type(d[101])

d.items()

d.values()

d.keys()

d.update({102:(45,67,89,34)})
d

print(d)

type(d[102])

d.[102].append(100)# cannot add since it is tuple

d[104].append(355)

d

print(d)

d[102]=(23,345,567,234)

print(d)

print(d)

d

type(d[101])

d[102]:{'a':{7,4,5,7},'b':(876,876,987),'c':['k',{'L':[12,34]}]}
d